// <auto-generated />
namespace WebProgramlamaProje.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class brand_and_category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(brand_and_category));
        
        string IMigrationMetadata.Id
        {
            get { return "202312090941102_brand_and_category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
