// <auto-generated />
namespace WebProgramlamaProje.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class district_city_region_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(district_city_region_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202312121457241_district_city_region_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
