// <auto-generated />
namespace WebProgramlamaProje.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Update_brand_category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_brand_category));
        
        string IMigrationMetadata.Id
        {
            get { return "202312091448010_Update_brand_category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
